[env:mcc_oss_readonly]
platform = espressif8266
board = esp12e
framework = arduino
monitor_speed = 115200
build_flags =
  -D MCC_OSS_FW_VERSION=\"MCC-OSS-READONLY-0.3.0\"
  -D ADC_INPUT_FULL_SCALE_V=3.02
  -D CELL_DIVIDER_RATIO=1.0
  -D MUX_SETTLE_US=1000
  -D ADC_SAMPLES=16
